### ISSUE TITLE
Раздел "статьи"

### ISSUE THREAD

**Issue by SkRYeR** [jetli13/ushu-uz#17]
Раздел статьи переименовать в "Стили и оружие Ушу" там иногда статьи именно по стилям добавляться будут.
Отдельно создать раздел "Статьи" там будут публиковаться только статьи самого В.Г. ,всякие поездки и т.д.
Раздел "Новости"  направить на раздел "Cтатьи" ,но чтоб отображались последние 2 выложенные.

**Comment by mursik** [comment]
"Раздел "Новости" направить на раздел "Cтатьи" ,но чтоб отображались последние 2 выложенные."
Это еще актуально ? смотрю там разная информация выложена

**Comment by jetli13** [comment]
> Раздел "Новости" направить на раздел "Cтатьи" ,но чтоб отображались последние 2 выложенные.

Родион, а зачем? кажется что не стоит это мешать?

**Comment by jetli13** [comment]
Поговорил с Родионом, таск закрываем
