### ISSUE TITLE
Правка на старницах

### ISSUE THREAD

**Issue by SkRYeR** [jetli13/ushu-uz#18]
на главной в цитате
"Во-первых, умение видеть и познавать самого себя.
Во-вторых, решимость, через преодоление глупости, слабости и всего ненужного.
И, наконец, искренность, чувствование, преданность, глубина души и понимание сердца."

подчеркнуть 3 строку тоже.
Выровнить текст в 1 и во второй странице.

Снизу подпись
"Ассоциация ушу республики Узбекистан" заменить на Ассоциация Традиционного ушу республики Узбекистан

**Comment by mursik** [comment]
Я так поняла эта задача закрыта? вроде все сделано
